name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: List files in current directory
        run: |
          pwd
          ls -l
          ls -l tests/

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python tests/test_generator.py
          python tests/test_data_loader.py

      - name: Deploy to DreamHost
        run: |
          rsync -avz --delete ./ dh_wzsc45@puppyipsum.com:~/puppyipsum.com/
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
