name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: List files in current directory
        run: ls -l

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover -s tests

      - name: Add SSH key to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 173.236.223.246 >> ~/.ssh/known_hosts

      - name: Setup SSH Key
        run: |
          eval $(ssh-agent -s)
          echo "${{ secrets.DEPLOY_KEY }}" | tr -d '\r' | ssh-add -
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy to DreamHost
        run: |
          rsync -avz --delete ./ dh_wzsc45@puppyipsum.com:~/puppyipsum.com/
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
